<a href="https://colab.research.google.com/github/Sarthak-Rajvaidya/Ml-Model-Fastapi/blob/main/ML_Model_with_fastapi.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.metrics import classification_report,accuracy_score
import numpy as np

In [2]:
df = pd.read_csv('/content/insurance.csv')

In [3]:
df.sample(5)

    age  weight  height  ...        city      occupation insurance_premium_category
76   62    99.1    1.50  ...      Mysore         retired                       High
74   63    71.1    1.54  ...   Jalandhar         retired                       High
86   35    66.0    1.89  ...   Hyderabad      freelancer                        Low
91   38   119.8    1.76  ...   Bangalore  government_job                        Low
71   38    54.1    1.81  ...  Chandigarh      unemployed                        Low

[5 rows x 8 columns]

In [4]:
df_feat = df.copy()

In [5]:
#feature engineering :- BMI
df_feat["bmi"] = df_feat["weight"]/(df_feat["height"]**2)

In [6]:
#feature 2 :- Age group
def age_group(age):
    if age < 25:
        return "young"
    elif age < 45:
        return "adult"
    elif age < 60:
        return "middle_aged"
    return "senior"

In [8]:
df_feat["age_group"] = df_feat["age"].apply(age_group)

In [9]:
#feature 3 :- lifestyle risk
def lifestyle_risk(row):
    if row["smoker"] and row["bmi"] > 30:
        return "high"
    elif row["smoker"] or row["bmi"] > 27:
        return "medium"
    else:
        return "low"

In [10]:
df_feat["lifestyle_risk"] = df_feat.apply(lifestyle_risk, axis=1)

In [11]:
tier_1_cities = ["Mumbai", "Delhi", "Bangalore", "Chennai", "Kolkata", "Hyderabad", "Pune"]
tier_2_cities = [
    "Jaipur", "Chandigarh", "Indore", "Lucknow", "Patna", "Ranchi", "Visakhapatnam", "Coimbatore",
    "Bhopal", "Nagpur", "Vadodara", "Surat", "Rajkot", "Jodhpur", "Raipur", "Amritsar", "Varanasi",
    "Agra", "Dehradun", "Mysore", "Jabalpur", "Guwahati", "Thiruvananthapuram", "Ludhiana", "Nashik",
    "Allahabad", "Udaipur", "Aurangabad", "Hubli", "Belgaum", "Salem", "Vijayawada", "Tiruchirappalli",
    "Bhavnagar", "Gwalior", "Dhanbad", "Bareilly", "Aligarh", "Gaya", "Kozhikode", "Warangal",
    "Kolhapur", "Bilaspur", "Jalandhar", "Noida", "Guntur", "Asansol", "Siliguri"
]

In [12]:
#feature 4 :-City Tier
def city_tier(city):
    if city in tier_1_cities:
        return 1
    elif city in tier_2_cities:
        return 2
    else:
        return 3

In [13]:
df_feat["city_tier"] = df_feat["city"].apply(city_tier)

In [15]:

df_feat.drop(columns=['age', 'weight', 'height', 'smoker', 'city'])[['income_lpa', 'occupation', 'bmi', 'age_group', 'lifestyle_risk', 'city_tier', 'insurance_premium_category']].sample(5)

    income_lpa   occupation  ...  city_tier insurance_premium_category
41        3.87      retired  ...          1                     Medium
2        36.64   freelancer  ...          2                        Low
5        50.00   freelancer  ...          3                     Medium
34        0.68      retired  ...          3                       High
51       28.95  private_job  ...          2                       High

[5 rows x 7 columns]

In [16]:
# Select features and target
X = df_feat[["bmi", "age_group", "lifestyle_risk", "city_tier", "income_lpa", "occupation"]]
y = df_feat["insurance_premium_category"]

In [17]:
X

          bmi    age_group  ... income_lpa      occupation
0   49.227482       senior  ...    2.92000         retired
1   30.189017        adult  ...   34.28000      freelancer
2   21.118382        adult  ...   36.64000      freelancer
3   45.535900        young  ...    3.34000         student
4   24.296875       senior  ...    3.94000         retired
..        ...          ...  ...        ...             ...
95  21.420747        adult  ...   19.64000  business_owner
96  47.984483        adult  ...   34.01000     private_job
97  18.765432  middle_aged  ...   44.86000      freelancer
98  30.521676        adult  ...   28.30000  business_owner
99  27.688778        adult  ...   28.16664  government_job

[100 rows x 6 columns]

In [18]:
y

0       High
1        Low
2        Low
3     Medium
4       High
       ...
95       Low
96       Low
97       Low
98       Low
99       Low
Name: insurance_premium_category, Length: 100, dtype: object

In [19]:
# Define categorical and numeric features
categorical_features = ["age_group", "lifestyle_risk", "occupation", "city_tier"]
numeric_features = ["bmi", "income_lpa"]

In [20]:
# Create column transformer for OHE
preprocessor = ColumnTransformer(
    transformers=[
        ("cat", OneHotEncoder(), categorical_features),
        ("num", "passthrough", numeric_features)
    ]
)